tmk/tmk_keyboard

common/command.c

Fixes a typo in console mode from "prameters" to "parameters".

Fixing typo in console mode

---

tmk_core/common/action.h
tmk_core/common/keymap.c

This allows a consumer to override this function while retaining the ability to reuse the default implementation.

Make action_for_key a weak symbol

---

converter/terminal_usb/keymap.c

I got a Model M terminal keyboard from a friend, model number 1399625. It has a layout typical of PC keyboards of the time, but it's still a PS/2 Scan Set 3 keyboard. Thanks for making it possible to use it!
I figured I probably needed to add a new keyboard layout and map to the terminal_usb converter. The result is in this pull request, but it is commented out by default. If you would like to see something named or layed out differently, please say so.
Some photo's of the keyboard:

Add 101-key Model M terminal keyboard

---

keyboard/hhkb/rn42/rn42.c

on OSX KC_MRWD and KC_MFFD are used instead of KC_MPRV and KC_MNXT

add KC_MRWD and KC_MFFD to rn42

---

tmk_core/common/action.c

if TAPPING_TOGGLE is 1, then tap a single time should toggle the mods on/off each tap.
Previously this was broken, this fixes it. This allows the same key to either hold (momentary mod) or tap (toggle mod, like capslock).

enable TAPPING_TOGGLE=1 to work correctly

---

tmk_core/common/keycode.h

This was causing compilation failures on any keymaps that used the `ERAS` key macro, which is only used in [news_usb](/tmk/tmk_keyboard/blob/a5f2892/converter/news_usb/keymap.c) currently.

Remove an errant comma trailing the KC_ERAS macro alias

---

tmk_core/protocol/serial_soft.c

SERIAL_SOFT_DEBUG can be defined in the `config.h`

remove  SERIAL_SOFT_DEBUG macro

---

tmk_core/common/command.c

Hello,
command.c defines the host_driver static variable but it is only used if KEYBOARD_LOCK_ENABLE is defined.
In my case KEYBOARD_LOCK_ENABLE is not defined so it triggers a warning.
This pull request encloses the declaration inside a #ifdef statement to avoid that warning.

Fix warning in command.c

---

tmk_core/common.mk

In my environment (Windows/Cygwin), compilation is very slow. Then I noticed that the git process is using a very high CPU usage when compiling.
I found the cause is that the current make rule attempts to obtain version information by calling git when compiling EVERY files. So after I moved the command substitution to a simply expanded variable, the compilation is much faster than before.
I think this change has not influence on version information. And it is quite effective in my environment.

core: Speed up compilation

---

tmk_core/protocol/bluefruit/bluefruit.c

This PR updates the macro names in bluefruit.c to the correct names as described in https://github.com/tmk/tmk_keyboard/issues/339

Update macro names in bluefruit protocol

---

converter/sun_usb/Makefile
converter/sun_usb/README
converter/sun_usb/command_extra.c
converter/sun_usb/config.h

**Background**
I found that the software serial timing wasn't quite right for my Sun Type 5c.  The software serial was able to receive just fine, but the transmitted bits were off enough (~850us by my measurements vs the required 833us for 1200 baud) that the Sun keyboard would respond with 0xFF for any transmitted command.   Since I had a 7404 inverter on hand, I made these changes to allow using the hardware serial on my Atmega 32u4 (Arduino Micro).  The keyboard works flawlessly.
**Changes**
This change adds an option to the Makefile to use the hardware serial support instead of software.  The default behavior is unchanged.  I have updated the documents to note this as well.
**Testing**
Tested hardware serial with a Sun Type 5c keyboard and a 7404 inverter.  Verified that the Software …

Add hardware serial support for sun_usb converter

---

README.md

Fixes a link made in this commit:
https://github.com/tmk/tmk_keyboard/commit/885e7adb18fb6039f0fe66de23e0622af923f7d1#diff-04c6e90faac2675aa89e2176d2eec7d8R3

README missing link

---

tmk_core/doc/keymap.md

I noticed that the Macro function documentation still has TBD so while I was in the area, thought I would add some more detail here, plus another function gotcha that wasn't clear from the documentation (action_layer_mods will assume the modifier is on the left side of the keyboard)

Update documentation for Macro function and action_layer_mods

---

converter/adb_usb/matrix.c

I think I found the cause and a solution for #35 which also happened on my ISO, Canadian Multilingual M3501.
Sample hid_listen output:
```
Waiting for device:.....
Listening:
Before init:
Scan: addr:2, reg3:6505
After init:
Scan: addr:2, reg3:6403
debug enabled.
Keyboard start.
```
With the 05 as expected for an ISO board. From what I could see. the two larger bytes changed from one boot to another.
On another note, I've seen the value return 03 (i.e. ANSI) when resetting and flashing the converter (here: an Arduino Pro Micro clone) without disconnecting for a few seconds.

adb_usb/matrix.c : changed size of handler_id from uint16_t to uint8_t

---

converter/xt_usb/keymap_common.h
tmk_core/protocol/xt.h

The functions `wait_clock_hi`, `wait_data_lo` and `wait_data_hi` are not used for the xt converter.

xt converter: remove unused functions; add XT_KEYMAP

---

keyboard/infinity_chibios/MEMO.txt
keyboard/teensy_lc_onekey/instructions.md
tmk_core/protocol/chibios/README.md

Moved all install documentation to `tmk_core/protocol/chibios/README.md` from both
- `keyboard/teensy_lc_onekey/instructions.md`
- `keyboard/infinity_chibios/MEMO.txt`
Tells people to check out the most recent stable version of [ChibiOS/ChibiOS](https://github.com/ChibiOS/ChibiOS), and changes the zip download to the branch `stable_17.6.x` from commit `a7df9a891067621e8e1a5c2a2c0ceada82403afe`
Also changed the zip download for [ChibiOS/ChibiOS-Contrib](https://github.com/ChibiOS/ChibiOS-Contrib) to master from commit `e1311c4db6cd366cf760673f769e925741ac0ad3`
From discussion in issue #490

Move all ChibiOS install documentation to once place

---

tmk_core/common/command.c

Gives a compile warning. Fixed it by adding an #if

core: Fix for unused function when compiling without MOUSEKEY_ENABLE

---

tmk_core/common/keyboard.c

* Fixed a bug where the time reported for keys inside a matrix scan would be different if the clock ticked halfway through scanning. 
* Improved performance by caching timer_read() and the col_mask rather than calculating them multiple times.

core: Improved performance, fixed nuances in timing

---

tmk_core/common/action_macro.h

* Macro definitions for typing modified keys more easily in TMK macros.
- Example: Ctrl+Alt+[Shift+]<key> can be entered with CTL_( ALT_( [S]T(key) ))
- AGR_ is for RAlt/AltGr input, useful with international system layouts.
* Macro definitions for typing OS specific Unicode input.
* For XOrg,    Unicode 4-digit hex input uses Ctrl+Shift+u, ####, Enter.
* For MacOS,   Unicode 4-digit hex Unicode input uses Alt+#### (as Alt equals Mac Option).
* For Windows, Unicode 4-digit decimal nr. input uses Alt+Keypad(####).

core: Add utility macros in action_macro.h

---

keyboard/stm32_f103_onekey/chconf.h
keyboard/stm32_f103_onekey/halconf.h
keyboard/stm32_f103_onekey/mcuconf.h
tmk_core/common/chibios/timer.c
tmk_core/protocol/chibios/usb_main.c
tmk_core/tool/chibios/chibios.mk

The stm32_f103_onekey code is out of date and cannot be compiled with the new version of Chibios, I try to fix it and now the code works.

compile STM32 with new version of ChibiOS

---

converter/ps2_usb/config.h

according to the code:
static uint8_t matrix[MATRIX_ROWS];
#define ROW(code)      (code>>3)
#define COL(code)      (code&0x07)
in converter/ps2_usb/matrix.c
ROW is decided by bits 7-4 of scancode
COL is decided by bits 2-0 of scancode

Correct the comments of matrix ROW and COL.

---

converter/terminal_usb/keymap.c

Correct four key remaps to achieve ANSI layout except backlash"\",if willing exchange backslah and enter to achieve ansi layout completely.

Redefine GRV,CAPS,RALT and RCTL

---

converter/terminal_usb/keymap.c

Adding support for the IBM 102 Terminal Keyboard ( #1386304 )
The 1386304 has a slightly different matrix than the 122/101 terminal keyboard.

Adding support for the IBM 102 Terminal Keyboard ( #1386304 )

---

converter/ibmpc_usb/ibmpc_usb.cpp
converter/ibmpc_usb/ibmpc_usb.hpp

See this thread for which keyboards I am referring to:
https://deskthority.net/viewtopic.php?f=2&t=25763
(Many of these keyboards are completely unbranded on the outside, and only the
PCB reads "TELEVIDEO ANSI Scan")
@tmk Are the .c files deprecated now, and I can safely ignore? Or do I need to port my changes to the .c files too?

Add support for the DEC layout Televideo Linear Space Invader keyboards to ibmpc_usb.

---

converter/ibmpc_usb/ibmpc_usb.cpp

The PS/2 controller code for Unicomp's current generation PS/2 keyboard sends the wrong scancodes when Ctrl + Pause (which should be Break) is pressed:
https://deskthority.net/viewtopic.php?f=2&t=25718
https://www.reddit.com/r/modelm/comments/n0u81o/anybody_out_there_rocking_a_ps2_unicomp_noticed/
Instead of it sending the Break sequence...
E0 7E E0 F0 7E
... representing a press of Scroll Lock, which is Break because Ctrl is being pressed, it instead sends...
E0 77
... representing a press of Num Lock, which is just the old way of getting Pause.
Since the E0 77 coming from the controller is not a normal sequence, this workaround does not interfere with Ctrl + Num Lock, which still Pauses as it should. It uses the same solution as the existing override to produce Break (for keyboards with …

Unicomp New Model M broken Pause/Break key fix
